apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: sgbaxi7jq-java-springboot-gitops
  description: This is GitOps manifest for sgbaxi7jq-java-springboot   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=sgbaxi7jq-java-springboot
    backstage.io/kubernetes-id: sgbaxi7jq-java-springboot 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: rhtap-rhdh-qe/sgbaxi7jq-java-springboot-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:sgbaxi7jq-java-springboot
